services:
#    admin.example:
#        class: AdminBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  admin.service.login:
    class:  AdminBundle\Service\LoginService
    arguments: ["@doctrine.orm.entity_manager"]
