core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /core

backend:
    resource: "@BackendBundle/Controller/"
    type:     annotation
    prefix:   /backend

frontend:
    resource: "@FrontendBundle/Controller/"
    type:     annotation
    prefix:   /
