# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html
security:

    encoders:
        BackendBundle\Entity\AdministratorEntity:
            algorithm: bcrypt

    providers:
        backend.administrator:
            entity:
                class: BackendBundle:AdministratorEntity
        frontend.customer:
            entity:
                class: CoreBundle:CustomerEntity

    firewalls:
        main:
            anonymous: ~
            form_login:
                login_path: backend_login