<?php

namespace Tests\Frontend\Controller;

use Tests\CoreBundle\Boot\TestWebWithDbDefaultData;

class DefaultControllerTest extends TestWebWithDbDefaultData
{
    protected static function createKernel(array $options = array())
    {
        return parent::createKernel($options); // TODO: Change the autogenerated stub
    }

    public function testIndex()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/');
        $this->assertCount(21, $crawler->filter('div.card-block .fa-database'));
        $this->assertEquals(200, $client->getResponse()->getStatusCode());
    }

    public function testCataloguePeripherals()
    {
        $client = static::createClient();

        $crawler = $client->request('GET', '/catalogue/Peripherals');
        $this->assertCount(4, $crawler->filter('div.card-block .fa-database'));
        $this->assertEquals(200, $client->getResponse()->getStatusCode());
    }
}
