services:
    frontend.service.order:
        class: FrontendBundle\Service\Db\OrderService
        arguments: ["@doctrine.orm.entity_manager", "@repository.order", "@repository.address"]
    frontend.service.db.registration:
        class:  FrontendBundle\Service\Db\RegistrationService
        arguments: ["@doctrine.orm.entity_manager", "@repository.customer", "@repository.address"]

    frontend.service.db.profile:
        class:  FrontendBundle\Service\Db\AccountService
        arguments: ["@doctrine.orm.entity_manager", "@repository.customer", "@repository.address"]

    frontend.service.db.customer:
        class:  CoreBundle\Service\Db\CustomerService
        arguments: ["@doctrine.orm.entity_manager", "@repository.customer", "@repository.address"]

    frontend.service.db.security:
        class:  CoreBundle\Service\Security\SecurityService
        arguments: ["@request_stack", "@security.token_storage", "@event_dispatcher", "@repository.customer"]

    frontend.service.category:
        class:  FrontendBundle\Service\Db\CategoryService
        arguments: ["@doctrine.orm.entity_manager", "@repository.category"]

    frontend.service.product:
        class: CoreBundle\Service\Db\ProductService
        arguments: ["@doctrine.orm.entity_manager", "@repository.product", "@repository.category", "@repository.image"]

    frontend.service.shopping.cart:
        class: FrontendBundle\Service\ShoppingCart\DbShoppingCartService
        arguments: ["@request_stack"]

    frontend.service.currency:
        class: FrontendBundle\Twig\Extension\CurrencyService
        arguments: ["@request_stack"]

    app.twig_extension:
        class: FrontendBundle\Twig\Extension\PriceExtension
        arguments: ["@frontend.service.currency"]
        public: false
        tags:
            - { name: twig.extension }