services:
#    admin.example:
#        class: BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  backend.service.login:
    class:  BackendBundle\Service\Db\LoginService
    arguments: ["@doctrine.orm.entity_manager"]
  backend.service.category:
    class:  BackendBundle\Service\Db\CategoryService
    arguments: ["@doctrine.orm.entity_manager"]
  backend.service.product:
    class:  BackendBundle\Service\Db\ProductService
    arguments: ["@doctrine.orm.entity_manager", "@backend.service.category"]