services:
#    admin.example:
#        class: BackendBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
  backend.service.login:
    class:  BackendBundle\Service\LoginService
    arguments: ["@doctrine.orm.entity_manager"]
